services:
  - type: web
    name: milltownabc
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node dist/index.cjs
    envVars:
      - key: NODE_ENV
        value: production
